/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwin (void)
{
  GtkWidget *mainwin;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolitem1;
  GtkWidget *addbtn;
  GtkWidget *toolitem2;
  GtkWidget *playbtn;
  GtkWidget *toolitem3;
  GtkWidget *button3;
  GtkWidget *vbox2;
  GtkWidget *label1;
  GtkWidget *volume;
  GtkWidget *vbox3;
  GtkWidget *label2;
  GtkWidget *playpos;
  GtkWidget *playlist;

  mainwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mainwin), "DeaDBeeF");
  gtk_window_set_default_size (GTK_WINDOW (mainwin), 750, 650);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwin), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox1), toolbar1, TRUE, TRUE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  addbtn = gtk_button_new_with_mnemonic ("Add");
  gtk_widget_show (addbtn);
  gtk_container_add (GTK_CONTAINER (toolitem1), addbtn);

  toolitem2 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem2);

  playbtn = gtk_button_new_with_mnemonic ("Play");
  gtk_widget_show (playbtn);
  gtk_container_add (GTK_CONTAINER (toolitem2), playbtn);

  toolitem3 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem3);

  button3 = gtk_button_new_with_mnemonic ("Stop");
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (toolitem3), button3);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, FALSE, TRUE, 0);

  label1 = gtk_label_new ("Volume");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox2), label1, FALSE, FALSE, 0);

  volume = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (100, 0, 100, 0, 0, 0)));
  gtk_widget_show (volume);
  gtk_box_pack_start (GTK_BOX (vbox2), volume, TRUE, TRUE, 0);
  gtk_widget_set_size_request (volume, 100, -1);
  gtk_scale_set_draw_value (GTK_SCALE (volume), FALSE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox3, FALSE, TRUE, 0);

  label2 = gtk_label_new ("Play position");
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox3), label2, FALSE, FALSE, 0);

  playpos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1000, 0, 0, 0)));
  gtk_widget_show (playpos);
  gtk_box_pack_start (GTK_BOX (vbox3), playpos, TRUE, TRUE, 0);
  gtk_widget_set_size_request (playpos, 200, -1);
  gtk_scale_set_draw_value (GTK_SCALE (playpos), FALSE);

  playlist = gtk_drawing_area_new ();
  gtk_widget_show (playlist);
  gtk_box_pack_start (GTK_BOX (vbox1), playlist, TRUE, TRUE, 0);
  gtk_widget_set_events (playlist, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK);

  g_signal_connect ((gpointer) mainwin, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) addbtn, "clicked",
                    G_CALLBACK (on_addbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) playbtn, "clicked",
                    G_CALLBACK (on_playbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) volume, "value_changed",
                    G_CALLBACK (on_volume_value_changed),
                    NULL);
  g_signal_connect ((gpointer) playpos, "value_changed",
                    G_CALLBACK (on_playpos_value_changed),
                    NULL);
  g_signal_connect ((gpointer) playlist, "configure_event",
                    G_CALLBACK (on_playlist_configure_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "expose_event",
                    G_CALLBACK (on_playlist_expose_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "realize",
                    G_CALLBACK (on_playlist_realize),
                    NULL);
  g_signal_connect ((gpointer) playlist, "button_press_event",
                    G_CALLBACK (on_playlist_button_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwin, mainwin, "mainwin");
  GLADE_HOOKUP_OBJECT (mainwin, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mainwin, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (mainwin, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (mainwin, addbtn, "addbtn");
  GLADE_HOOKUP_OBJECT (mainwin, toolitem2, "toolitem2");
  GLADE_HOOKUP_OBJECT (mainwin, playbtn, "playbtn");
  GLADE_HOOKUP_OBJECT (mainwin, toolitem3, "toolitem3");
  GLADE_HOOKUP_OBJECT (mainwin, button3, "button3");
  GLADE_HOOKUP_OBJECT (mainwin, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (mainwin, label1, "label1");
  GLADE_HOOKUP_OBJECT (mainwin, volume, "volume");
  GLADE_HOOKUP_OBJECT (mainwin, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (mainwin, label2, "label2");
  GLADE_HOOKUP_OBJECT (mainwin, playpos, "playpos");
  GLADE_HOOKUP_OBJECT (mainwin, playlist, "playlist");

  return mainwin;
}

