./portable_postbuild.sh

#sudo cp ./deadbeef /usr/local/bin/
#sudo cp ./plugins/nullout/.libs/nullout.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/cdda/.libs/cdda.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/flac/.libs/flac.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/alsa/.libs/alsa.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/mpgmad/.libs/mpgmad.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/hotkeys/.libs/hotkeys.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/vtx/.libs/vtx.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/ffap/.libs/ffap.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/wavpack/.libs/wavpack.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/vorbis/.libs/vorbis.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/oss/.libs/oss.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/vfs_curl/.libs/vfs_curl.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/ffmpeg/.libs/ffmpeg.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/lastfm/.libs/lastfm.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/sid/.libs/sid.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/adplug/.libs/adplug.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/gtkui/.libs/gtkui.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/sndfile/.libs/sndfile.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/pulse/.libs/pulse.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/artwork/.libs/artwork.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/supereq/.libs/supereq.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/gme/.libs/gme.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/dumb/.libs/dumb.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/notify/.libs/notify.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/musepack/.libs/musepack.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/wildmidi/.libs/wildmidi.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/tta/.libs/tta.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/dca/.libs/dca.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/aac/.libs/aac.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/mms/.libs/mms.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/shn/.libs/shn.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/ao/.libs/ao.so /usr/local/lib/deadbeef/
#sudo cp ./plugins/shellexec/.libs/shellexec.so /usr/local/lib/deadbeef/
