#!/usr/bin/env perl
use strict;
use warnings;

use FindBin qw'$Bin';
use lib "$FindBin::Bin";
use lib "$FindBin::Bin/perl_lib";
BEGIN { $ENV{PERL_JSON_BACKEND} = 0 }
use JSON -support_by_pp;
use Data::Dumper;

open F,"<api.json" or die "failed to read api.json\n";
my $api;
{
    local $/;
    $api = <F>;
}
close F;

my $json = JSON->new;
$json->relaxed([1]);
$json->allow_singlequote([1]);
$json->allow_barekey([1]);

$api = $json->decode($api);
#print Dumper($api)."\n";
print "/* WARNING: autogenerated file */\n";
print "#include \"duktape.h\"\n";
print "#include \"../../deadbeef.h\"\n\n";
print "#include \"bindings.h\"\n\n";
print "extern DB_functions_t *deadbeef;\n\n";

# int constants
print "void bind_int_constants (duk_context *ctx) {\n";
print "    duk_push_global_object(ctx);\n";
my $int_constants = $api->{int_constants};
foreach my $c (keys %$int_constants) {
    print "    duk_push_int(ctx, $int_constants->{$c});\n";
    print "    duk_put_prop_string(ctx, -2, \"$c\");\n";
}
print "    duk_pop(ctx);\n";
print "}\n\n";

my %ret_converters = (
);

my $functions = $api->{functions};

# function impls
foreach my $c (keys %$functions) {
    my $f = $functions->{$c};
	print "int\njs_impl_$f->{name} (duk_context *ctx) {\n";
	if (!$f->{ret}) {
		$f->{ret} = 'void';
	}
	if (ref ($f->{args}) eq 'ARRAY') {
		my $idx = 0;
		foreach my $type (@{$f->{args}}) {
			my $convname = $type;
			$convname =~ s/\*/_ptr/g;
			$convname =~ s/[^A-Za-z0-9_]/_/g;
			print "    $type arg$idx = js_init_" . $convname . "_argument (ctx, $idx);\n";
			$idx++;
		}
	}

	if ($f->{ret} ne 'void') {
		print "    $f->{ret} ret = ";
	}
	else {
		print "    ";
	}

	print "deadbeef->$c (";
	if (ref ($f->{args}) eq 'ARRAY') {
		my $idx = 0;
		foreach my $type (@{$f->{args}}) {
			print ', ' if $idx;
			print "arg$idx";
			$idx++;
		}
	}
	elsif ($f->{args} ne 'void') {
		die "Invalid argument list: \n" . Dumper($f) . "\n";
	}
	print ");\n";


	if ($f->{ret} eq 'void') {
		print "    return 0;\n";
	}
	else {
		my $convname = $f->{ret};
		$convname =~ s/\*/_ptr/g;
		$convname =~ s/[^A-Za-z0-9_]/_/g;
		print '    js_return_' . $convname . "_value (ctx, ret);\n";
		print "    return 1;\n";
	}
	print "}\n\n";
}

# functions
print "void bind_functions (duk_context *ctx) {\n";
print "    duk_push_global_object(ctx);\n";
foreach my $c (keys %$functions) {
    my $f = $functions->{$c};
    print "    duk_push_c_function(ctx, js_impl_$f->{name}, 0);\n";
    print "    duk_put_prop_string(ctx, -2, \"$f->{name}\");\n";
}
print "    duk_pop(ctx);\n";
print "}\n\n";

# util
print "void duktape_bind_all (duk_context *ctx) {\n";
print "    bind_int_constants(ctx);\n";
print "    bind_functions(ctx);\n";
print "}\n\n";
