FROM deadbeef-builder-player-clang-20.04

WORKDIR /usr/src/deadbeef
COPY . /usr/src/deadbeef
ENV BUILD_OS_NAME=linux

RUN apt-get -qq update
RUN apt-get install -y -qq libjansson-dev

RUN rm -rf m4
RUN rm ltmain.sh
RUN ./autogen.sh
RUN CC=clang CXX=clang++ ./configure
RUN CC=clang CXX=clang++  make distcheck
