/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwin (void)
{
  GtkWidget *mainwin;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *open;
  GtkWidget *image312;
  GtkWidget *separator2;
  GtkWidget *add_files;
  GtkWidget *image313;
  GtkWidget *add_folders;
  GtkWidget *image314;
  GtkWidget *add_audio_cd;
  GtkWidget *image315;
  GtkWidget *add_location1;
  GtkWidget *separatormenuitem1;
  GtkWidget *playlist_load;
  GtkWidget *playlist_save;
  GtkWidget *playlist_save_as;
  GtkWidget *separator8;
  GtkWidget *quit;
  GtkWidget *image316;
  GtkWidget *edit1;
  GtkWidget *edit1_menu;
  GtkWidget *clear1;
  GtkWidget *image317;
  GtkWidget *select_all1;
  GtkWidget *selection1;
  GtkWidget *selection1_menu;
  GtkWidget *remove1;
  GtkWidget *image318;
  GtkWidget *crop1;
  GtkWidget *find1;
  GtkWidget *separator5;
  GtkWidget *preferences;
  GtkWidget *view1;
  GtkWidget *view1_menu;
  GtkWidget *view_status_bar;
  GtkWidget *view_headers;
  GtkWidget *playback1;
  GtkWidget *playback1_menu;
  GtkWidget *order1;
  GtkWidget *order1_menu;
  GSList *order_linear_group = NULL;
  GtkWidget *order_linear;
  GtkWidget *order_shuffle;
  GtkWidget *order_random;
  GtkWidget *looping1;
  GtkWidget *looping1_menu;
  GSList *loop_all_group = NULL;
  GtkWidget *loop_all;
  GtkWidget *loop_single;
  GtkWidget *loop_disable;
  GtkWidget *scroll_follows_playback;
  GtkWidget *cursor_follows_playback;
  GtkWidget *stop_after_current;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *help1;
  GtkWidget *image319;
  GtkWidget *changelog1;
  GtkWidget *separator10;
  GtkWidget *gpl1;
  GtkWidget *lgpl1;
  GtkWidget *separator9;
  GtkWidget *about1;
  GtkWidget *image320;
  GtkWidget *hbox2;
  GtkWidget *hbox3;
  GtkWidget *stopbtn;
  GtkWidget *image128;
  GtkWidget *playbtn;
  GtkWidget *image2;
  GtkWidget *pausebtn;
  GtkWidget *image3;
  GtkWidget *prevbtn;
  GtkWidget *image4;
  GtkWidget *nextbtn;
  GtkWidget *image5;
  GtkWidget *seekbar;
  GtkWidget *volumebar;
  GtkWidget *frame1;
  GtkWidget *table1;
  GtkWidget *_;
  GtkWidget *vbox3;
  GtkWidget *header;
  GtkWidget *playlist;
  GtkWidget *playscroll;
  GtkWidget *playhscroll;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  mainwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_events (mainwin, GDK_KEY_PRESS_MASK);
  gtk_window_set_title (GTK_WINDOW (mainwin), "DeaDBeeF");
  gtk_window_set_default_size (GTK_WINDOW (mainwin), 500, 300);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwin), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  open = gtk_image_menu_item_new_with_mnemonic ("_Open file(s)");
  gtk_widget_show (open);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open);
  gtk_widget_add_accelerator (open, "activate", accel_group,
                              GDK_O, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image312 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image312);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (open), image312);

  separator2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  add_files = gtk_image_menu_item_new_with_mnemonic ("Add file(s)");
  gtk_widget_show (add_files);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), add_files);

  image313 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image313);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_files), image313);

  add_folders = gtk_image_menu_item_new_with_mnemonic ("Add folder(s)");
  gtk_widget_show (add_folders);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), add_folders);

  image314 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image314);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_folders), image314);

  add_audio_cd = gtk_image_menu_item_new_with_mnemonic ("Add Audio CD");
  gtk_widget_show (add_audio_cd);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), add_audio_cd);

  image315 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image315);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (add_audio_cd), image315);

  add_location1 = gtk_menu_item_new_with_mnemonic ("Add location");
  gtk_widget_show (add_location1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), add_location1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  playlist_load = gtk_menu_item_new_with_mnemonic ("Load playlist");
  gtk_widget_show (playlist_load);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), playlist_load);

  playlist_save = gtk_menu_item_new_with_mnemonic ("Save playlist");
  gtk_widget_show (playlist_save);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), playlist_save);

  playlist_save_as = gtk_menu_item_new_with_mnemonic ("Save playlist as");
  gtk_widget_show (playlist_save_as);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), playlist_save_as);

  separator8 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator8);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator8);
  gtk_widget_set_sensitive (separator8, FALSE);

  quit = gtk_image_menu_item_new_with_mnemonic ("_Quit");
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit);
  gtk_widget_add_accelerator (quit, "activate", accel_group,
                              GDK_Q, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image316 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image316);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit), image316);

  edit1 = gtk_menu_item_new_with_mnemonic ("_Edit");
  gtk_widget_show (edit1);
  gtk_container_add (GTK_CONTAINER (menubar1), edit1);

  edit1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit1), edit1_menu);

  clear1 = gtk_image_menu_item_new_with_mnemonic ("_Clear");
  gtk_widget_show (clear1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), clear1);

  image317 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image317);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (clear1), image317);

  select_all1 = gtk_menu_item_new_with_mnemonic ("Select all");
  gtk_widget_show (select_all1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), select_all1);
  gtk_widget_add_accelerator (select_all1, "activate", accel_group,
                              GDK_A, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  selection1 = gtk_menu_item_new_with_mnemonic ("Selection");
  gtk_widget_show (selection1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), selection1);

  selection1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (selection1), selection1_menu);

  remove1 = gtk_image_menu_item_new_with_mnemonic ("Remove");
  gtk_widget_show (remove1);
  gtk_container_add (GTK_CONTAINER (selection1_menu), remove1);

  image318 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image318);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (remove1), image318);

  crop1 = gtk_menu_item_new_with_mnemonic ("Crop");
  gtk_widget_show (crop1);
  gtk_container_add (GTK_CONTAINER (selection1_menu), crop1);

  find1 = gtk_menu_item_new_with_mnemonic ("_Find");
  gtk_widget_show (find1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), find1);
  gtk_widget_add_accelerator (find1, "activate", accel_group,
                              GDK_F, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator5 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (edit1_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  preferences = gtk_menu_item_new_with_mnemonic ("Preferences");
  gtk_widget_show (preferences);
  gtk_container_add (GTK_CONTAINER (edit1_menu), preferences);

  view1 = gtk_menu_item_new_with_mnemonic ("_View");
  gtk_widget_show (view1);
  gtk_container_add (GTK_CONTAINER (menubar1), view1);

  view1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (view1), view1_menu);

  view_status_bar = gtk_check_menu_item_new_with_mnemonic ("Status bar");
  gtk_widget_show (view_status_bar);
  gtk_container_add (GTK_CONTAINER (view1_menu), view_status_bar);

  view_headers = gtk_check_menu_item_new_with_mnemonic ("Column headers");
  gtk_widget_show (view_headers);
  gtk_container_add (GTK_CONTAINER (view1_menu), view_headers);

  playback1 = gtk_menu_item_new_with_mnemonic ("_Playback");
  gtk_widget_show (playback1);
  gtk_container_add (GTK_CONTAINER (menubar1), playback1);

  playback1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (playback1), playback1_menu);

  order1 = gtk_menu_item_new_with_mnemonic ("Order");
  gtk_widget_show (order1);
  gtk_container_add (GTK_CONTAINER (playback1_menu), order1);

  order1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (order1), order1_menu);

  order_linear = gtk_radio_menu_item_new_with_mnemonic (order_linear_group, "Linear");
  order_linear_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (order_linear));
  gtk_widget_show (order_linear);
  gtk_container_add (GTK_CONTAINER (order1_menu), order_linear);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (order_linear), TRUE);

  order_shuffle = gtk_radio_menu_item_new_with_mnemonic (order_linear_group, "Shuffle");
  order_linear_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (order_shuffle));
  gtk_widget_show (order_shuffle);
  gtk_container_add (GTK_CONTAINER (order1_menu), order_shuffle);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (order_shuffle), TRUE);

  order_random = gtk_radio_menu_item_new_with_mnemonic (order_linear_group, "Random");
  order_linear_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (order_random));
  gtk_widget_show (order_random);
  gtk_container_add (GTK_CONTAINER (order1_menu), order_random);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (order_random), TRUE);

  looping1 = gtk_menu_item_new_with_mnemonic ("Looping");
  gtk_widget_show (looping1);
  gtk_container_add (GTK_CONTAINER (playback1_menu), looping1);

  looping1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (looping1), looping1_menu);

  loop_all = gtk_radio_menu_item_new_with_mnemonic (loop_all_group, "Loop All");
  loop_all_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (loop_all));
  gtk_widget_show (loop_all);
  gtk_container_add (GTK_CONTAINER (looping1_menu), loop_all);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (loop_all), TRUE);

  loop_single = gtk_radio_menu_item_new_with_mnemonic (loop_all_group, "Loop Single Song");
  loop_all_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (loop_single));
  gtk_widget_show (loop_single);
  gtk_container_add (GTK_CONTAINER (looping1_menu), loop_single);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (loop_single), TRUE);

  loop_disable = gtk_radio_menu_item_new_with_mnemonic (loop_all_group, "Don't Loop");
  loop_all_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (loop_disable));
  gtk_widget_show (loop_disable);
  gtk_container_add (GTK_CONTAINER (looping1_menu), loop_disable);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (loop_disable), TRUE);

  scroll_follows_playback = gtk_check_menu_item_new_with_mnemonic ("Scroll follows playback");
  gtk_widget_show (scroll_follows_playback);
  gtk_container_add (GTK_CONTAINER (playback1_menu), scroll_follows_playback);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (scroll_follows_playback), TRUE);

  cursor_follows_playback = gtk_check_menu_item_new_with_mnemonic ("Cursor follows playback");
  gtk_widget_show (cursor_follows_playback);
  gtk_container_add (GTK_CONTAINER (playback1_menu), cursor_follows_playback);

  stop_after_current = gtk_check_menu_item_new_with_mnemonic ("Stop after current");
  gtk_widget_show (stop_after_current);
  gtk_container_add (GTK_CONTAINER (playback1_menu), stop_after_current);
  gtk_widget_add_accelerator (stop_after_current, "activate", accel_group,
                              GDK_M, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  help1 = gtk_image_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), help1);

  image319 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image319);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (help1), image319);

  changelog1 = gtk_menu_item_new_with_mnemonic ("_ChangeLog");
  gtk_widget_show (changelog1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), changelog1);

  separator10 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator10);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separator10);
  gtk_widget_set_sensitive (separator10, FALSE);

  gpl1 = gtk_menu_item_new_with_mnemonic ("_GPLv2");
  gtk_widget_show (gpl1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), gpl1);

  lgpl1 = gtk_menu_item_new_with_mnemonic ("_LGPLv2.1");
  gtk_widget_show (lgpl1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), lgpl1);

  separator9 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator9);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separator9);
  gtk_widget_set_sensitive (separator9, FALSE);

  about1 = gtk_image_menu_item_new_with_mnemonic ("_About");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  image320 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image320);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about1), image320);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (hbox2), hbox3, FALSE, TRUE, 0);

  stopbtn = gtk_button_new ();
  gtk_widget_show (stopbtn);
  gtk_box_pack_start (GTK_BOX (hbox3), stopbtn, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (stopbtn, GTK_CAN_FOCUS);
  gtk_widget_add_accelerator (stopbtn, "activate", accel_group,
                              GDK_v, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (stopbtn), GTK_RELIEF_NONE);

  image128 = gtk_image_new_from_stock ("gtk-media-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image128);
  gtk_container_add (GTK_CONTAINER (stopbtn), image128);

  playbtn = gtk_button_new ();
  gtk_widget_show (playbtn);
  gtk_box_pack_start (GTK_BOX (hbox3), playbtn, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (playbtn, GTK_CAN_FOCUS);
  gtk_widget_add_accelerator (playbtn, "activate", accel_group,
                              GDK_x, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (playbtn, "activate", accel_group,
                              GDK_Return, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (playbtn), GTK_RELIEF_NONE);

  image2 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (playbtn), image2);

  pausebtn = gtk_button_new ();
  gtk_widget_show (pausebtn);
  gtk_box_pack_start (GTK_BOX (hbox3), pausebtn, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (pausebtn, GTK_CAN_FOCUS);
  gtk_widget_add_accelerator (pausebtn, "activate", accel_group,
                              GDK_c, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (pausebtn, "activate", accel_group,
                              GDK_p, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (pausebtn), GTK_RELIEF_NONE);

  image3 = gtk_image_new_from_stock ("gtk-media-pause", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (pausebtn), image3);

  prevbtn = gtk_button_new ();
  gtk_widget_show (prevbtn);
  gtk_box_pack_start (GTK_BOX (hbox3), prevbtn, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (prevbtn, GTK_CAN_FOCUS);
  gtk_widget_add_accelerator (prevbtn, "activate", accel_group,
                              GDK_z, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (prevbtn), GTK_RELIEF_NONE);

  image4 = gtk_image_new_from_stock ("gtk-media-previous", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (prevbtn), image4);

  nextbtn = gtk_button_new ();
  gtk_widget_show (nextbtn);
  gtk_box_pack_start (GTK_BOX (hbox3), nextbtn, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (nextbtn, GTK_CAN_FOCUS);
  gtk_widget_add_accelerator (nextbtn, "activate", accel_group,
                              GDK_b, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (nextbtn), GTK_RELIEF_NONE);

  image5 = gtk_image_new_from_stock ("gtk-media-next", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (nextbtn), image5);

  seekbar = gtk_drawing_area_new ();
  gtk_widget_show (seekbar);
  gtk_box_pack_start (GTK_BOX (hbox2), seekbar, TRUE, TRUE, 2);
  gtk_widget_set_size_request (seekbar, 200, -1);
  gtk_widget_set_events (seekbar, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  volumebar = gtk_drawing_area_new ();
  gtk_widget_show (volumebar);
  gtk_box_pack_start (GTK_BOX (hbox2), volumebar, FALSE, TRUE, 2);
  gtk_widget_set_size_request (volumebar, 70, -1);
  gtk_widget_set_events (volumebar, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 1);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame1), table1);

  _ = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (_);
  gtk_table_attach (GTK_TABLE (table1), _, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (_), vbox3, TRUE, TRUE, 0);

  header = gtk_drawing_area_new ();
  gtk_widget_show (header);
  gtk_box_pack_start (GTK_BOX (vbox3), header, FALSE, TRUE, 0);
  gtk_widget_set_size_request (header, -1, 24);
  gtk_widget_set_events (header, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  playlist = gtk_drawing_area_new ();
  gtk_widget_show (playlist);
  gtk_box_pack_start (GTK_BOX (vbox3), playlist, TRUE, TRUE, 0);
  gtk_widget_set_events (playlist, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK);

  playscroll = gtk_vscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 1, 0, 0)));
  gtk_widget_show (playscroll);
  gtk_table_attach (GTK_TABLE (table1), playscroll, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  playhscroll = gtk_hscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_show (playhscroll);
  gtk_table_attach (GTK_TABLE (table1), playhscroll, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) mainwin, "key_press_event",
                    G_CALLBACK (on_mainwin_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) mainwin, "delete_event",
                    G_CALLBACK (on_mainwin_delete_event),
                    NULL);
  g_signal_connect ((gpointer) mainwin, "configure_event",
                    G_CALLBACK (on_mainwin_configure_event),
                    NULL);
  g_signal_connect ((gpointer) mainwin, "window_state_event",
                    G_CALLBACK (on_mainwin_window_state_event),
                    NULL);
  g_signal_connect ((gpointer) open, "activate",
                    G_CALLBACK (on_open_activate),
                    NULL);
  g_signal_connect ((gpointer) add_files, "activate",
                    G_CALLBACK (on_add_files_activate),
                    NULL);
  g_signal_connect ((gpointer) add_folders, "activate",
                    G_CALLBACK (on_add_folders_activate),
                    NULL);
  g_signal_connect ((gpointer) add_audio_cd, "activate",
                    G_CALLBACK (on_add_audio_cd_activate),
                    NULL);
  g_signal_connect ((gpointer) add_location1, "activate",
                    G_CALLBACK (on_add_location_activate),
                    NULL);
  g_signal_connect ((gpointer) playlist_load, "activate",
                    G_CALLBACK (on_playlist_load_activate),
                    NULL);
  g_signal_connect ((gpointer) playlist_save, "activate",
                    G_CALLBACK (on_playlist_save_activate),
                    NULL);
  g_signal_connect ((gpointer) playlist_save_as, "activate",
                    G_CALLBACK (on_playlist_save_as_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) clear1, "activate",
                    G_CALLBACK (on_clear1_activate),
                    NULL);
  g_signal_connect ((gpointer) select_all1, "activate",
                    G_CALLBACK (on_select_all1_activate),
                    NULL);
  g_signal_connect ((gpointer) remove1, "activate",
                    G_CALLBACK (on_remove1_activate),
                    NULL);
  g_signal_connect ((gpointer) crop1, "activate",
                    G_CALLBACK (on_crop1_activate),
                    NULL);
  g_signal_connect ((gpointer) find1, "activate",
                    G_CALLBACK (on_find_activate),
                    NULL);
  g_signal_connect ((gpointer) preferences, "activate",
                    G_CALLBACK (on_preferences_activate),
                    NULL);
  g_signal_connect ((gpointer) view_status_bar, "activate",
                    G_CALLBACK (on_toggle_status_bar_activate),
                    NULL);
  g_signal_connect ((gpointer) view_headers, "activate",
                    G_CALLBACK (on_toggle_column_headers_activate),
                    NULL);
  g_signal_connect ((gpointer) order_linear, "activate",
                    G_CALLBACK (on_order_linear_activate),
                    NULL);
  g_signal_connect ((gpointer) order_shuffle, "activate",
                    G_CALLBACK (on_order_shuffle_activate),
                    NULL);
  g_signal_connect ((gpointer) order_random, "activate",
                    G_CALLBACK (on_order_random_activate),
                    NULL);
  g_signal_connect ((gpointer) loop_all, "activate",
                    G_CALLBACK (on_loop_all_activate),
                    NULL);
  g_signal_connect ((gpointer) loop_single, "activate",
                    G_CALLBACK (on_loop_single_activate),
                    NULL);
  g_signal_connect ((gpointer) loop_disable, "activate",
                    G_CALLBACK (on_loop_disable_activate),
                    NULL);
  g_signal_connect ((gpointer) scroll_follows_playback, "activate",
                    G_CALLBACK (on_scroll_follows_playback_activate),
                    NULL);
  g_signal_connect ((gpointer) cursor_follows_playback, "activate",
                    G_CALLBACK (on_cursor_follows_playback_activate),
                    NULL);
  g_signal_connect ((gpointer) stop_after_current, "activate",
                    G_CALLBACK (on_stop_after_current_activate),
                    NULL);
  g_signal_connect ((gpointer) help1, "activate",
                    G_CALLBACK (on_help1_activate),
                    NULL);
  g_signal_connect ((gpointer) changelog1, "activate",
                    G_CALLBACK (on_changelog1_activate),
                    NULL);
  g_signal_connect ((gpointer) gpl1, "activate",
                    G_CALLBACK (on_gpl1_activate),
                    NULL);
  g_signal_connect ((gpointer) lgpl1, "activate",
                    G_CALLBACK (on_lgpl1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) stopbtn, "clicked",
                    G_CALLBACK (on_stopbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) playbtn, "clicked",
                    G_CALLBACK (on_playbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) pausebtn, "clicked",
                    G_CALLBACK (on_pausebtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) prevbtn, "clicked",
                    G_CALLBACK (on_prevbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) nextbtn, "clicked",
                    G_CALLBACK (on_nextbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) seekbar, "button_press_event",
                    G_CALLBACK (on_seekbar_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) seekbar, "button_release_event",
                    G_CALLBACK (on_seekbar_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) seekbar, "configure_event",
                    G_CALLBACK (on_seekbar_configure_event),
                    NULL);
  g_signal_connect ((gpointer) seekbar, "expose_event",
                    G_CALLBACK (on_seekbar_expose_event),
                    NULL);
  g_signal_connect ((gpointer) seekbar, "motion_notify_event",
                    G_CALLBACK (on_seekbar_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) volumebar, "button_press_event",
                    G_CALLBACK (on_volumebar_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) volumebar, "button_release_event",
                    G_CALLBACK (on_volumebar_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) volumebar, "configure_event",
                    G_CALLBACK (on_volumebar_configure_event),
                    NULL);
  g_signal_connect ((gpointer) volumebar, "expose_event",
                    G_CALLBACK (on_volumebar_expose_event),
                    NULL);
  g_signal_connect ((gpointer) volumebar, "motion_notify_event",
                    G_CALLBACK (on_volumebar_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) volumebar, "scroll_event",
                    G_CALLBACK (on_volumebar_scroll_event),
                    NULL);
  g_signal_connect ((gpointer) header, "expose_event",
                    G_CALLBACK (on_header_expose_event),
                    NULL);
  g_signal_connect ((gpointer) header, "configure_event",
                    G_CALLBACK (on_header_configure_event),
                    NULL);
  g_signal_connect ((gpointer) header, "realize",
                    G_CALLBACK (on_header_realize),
                    NULL);
  g_signal_connect ((gpointer) header, "motion_notify_event",
                    G_CALLBACK (on_header_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) header, "button_press_event",
                    G_CALLBACK (on_header_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) header, "button_release_event",
                    G_CALLBACK (on_header_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "configure_event",
                    G_CALLBACK (on_playlist_configure_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "expose_event",
                    G_CALLBACK (on_playlist_expose_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "realize",
                    G_CALLBACK (on_playlist_realize),
                    NULL);
  g_signal_connect ((gpointer) playlist, "button_press_event",
                    G_CALLBACK (on_playlist_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "scroll_event",
                    G_CALLBACK (on_playlist_scroll_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_begin",
                    G_CALLBACK (on_playlist_drag_begin),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_motion",
                    G_CALLBACK (on_playlist_drag_motion),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_drop",
                    G_CALLBACK (on_playlist_drag_drop),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_data_get",
                    G_CALLBACK (on_playlist_drag_data_get),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_end",
                    G_CALLBACK (on_playlist_drag_end),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_failed",
                    G_CALLBACK (on_playlist_drag_failed),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_leave",
                    G_CALLBACK (on_playlist_drag_leave),
                    NULL);
  g_signal_connect ((gpointer) playlist, "button_release_event",
                    G_CALLBACK (on_playlist_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "motion_notify_event",
                    G_CALLBACK (on_playlist_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_data_received",
                    G_CALLBACK (on_playlist_drag_data_received),
                    NULL);
  g_signal_connect ((gpointer) playlist, "drag_data_delete",
                    G_CALLBACK (on_playlist_drag_data_delete),
                    NULL);
  g_signal_connect ((gpointer) playscroll, "value_changed",
                    G_CALLBACK (on_playscroll_value_changed),
                    NULL);
  g_signal_connect ((gpointer) playhscroll, "value_changed",
                    G_CALLBACK (on_playhscroll_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwin, mainwin, "mainwin");
  GLADE_HOOKUP_OBJECT (mainwin, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwin, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (mainwin, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (mainwin, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (mainwin, open, "open");
  GLADE_HOOKUP_OBJECT (mainwin, image312, "image312");
  GLADE_HOOKUP_OBJECT (mainwin, separator2, "separator2");
  GLADE_HOOKUP_OBJECT (mainwin, add_files, "add_files");
  GLADE_HOOKUP_OBJECT (mainwin, image313, "image313");
  GLADE_HOOKUP_OBJECT (mainwin, add_folders, "add_folders");
  GLADE_HOOKUP_OBJECT (mainwin, image314, "image314");
  GLADE_HOOKUP_OBJECT (mainwin, add_audio_cd, "add_audio_cd");
  GLADE_HOOKUP_OBJECT (mainwin, image315, "image315");
  GLADE_HOOKUP_OBJECT (mainwin, add_location1, "add_location1");
  GLADE_HOOKUP_OBJECT (mainwin, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (mainwin, playlist_load, "playlist_load");
  GLADE_HOOKUP_OBJECT (mainwin, playlist_save, "playlist_save");
  GLADE_HOOKUP_OBJECT (mainwin, playlist_save_as, "playlist_save_as");
  GLADE_HOOKUP_OBJECT (mainwin, separator8, "separator8");
  GLADE_HOOKUP_OBJECT (mainwin, quit, "quit");
  GLADE_HOOKUP_OBJECT (mainwin, image316, "image316");
  GLADE_HOOKUP_OBJECT (mainwin, edit1, "edit1");
  GLADE_HOOKUP_OBJECT (mainwin, edit1_menu, "edit1_menu");
  GLADE_HOOKUP_OBJECT (mainwin, clear1, "clear1");
  GLADE_HOOKUP_OBJECT (mainwin, image317, "image317");
  GLADE_HOOKUP_OBJECT (mainwin, select_all1, "select_all1");
  GLADE_HOOKUP_OBJECT (mainwin, selection1, "selection1");
  GLADE_HOOKUP_OBJECT (mainwin, selection1_menu, "selection1_menu");
  GLADE_HOOKUP_OBJECT (mainwin, remove1, "remove1");
  GLADE_HOOKUP_OBJECT (mainwin, image318, "image318");
  GLADE_HOOKUP_OBJECT (mainwin, crop1, "crop1");
  GLADE_HOOKUP_OBJECT (mainwin, find1, "find1");
  GLADE_HOOKUP_OBJECT (mainwin, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (mainwin, preferences, "preferences");
  GLADE_HOOKUP_OBJECT (mainwin, view1, "view1");
  GLADE_HOOKUP_OBJECT (mainwin, view1_menu, "view1_menu");
  GLADE_HOOKUP_OBJECT (mainwin, view_status_bar, "view_status_bar");
  GLADE_HOOKUP_OBJECT (mainwin, view_headers, "view_headers");
  GLADE_HOOKUP_OBJECT (mainwin, playback1, "playback1");
  GLADE_HOOKUP_OBJECT (mainwin, playback1_menu, "playback1_menu");
  GLADE_HOOKUP_OBJECT (mainwin, order1, "order1");
  GLADE_HOOKUP_OBJECT (mainwin, order1_menu, "order1_menu");
  GLADE_HOOKUP_OBJECT (mainwin, order_linear, "order_linear");
  GLADE_HOOKUP_OBJECT (mainwin, order_shuffle, "order_shuffle");
  GLADE_HOOKUP_OBJECT (mainwin, order_random, "order_random");
  GLADE_HOOKUP_OBJECT (mainwin, looping1, "looping1");
  GLADE_HOOKUP_OBJECT (mainwin, looping1_menu, "looping1_menu");
  GLADE_HOOKUP_OBJECT (mainwin, loop_all, "loop_all");
  GLADE_HOOKUP_OBJECT (mainwin, loop_single, "loop_single");
  GLADE_HOOKUP_OBJECT (mainwin, loop_disable, "loop_disable");
  GLADE_HOOKUP_OBJECT (mainwin, scroll_follows_playback, "scroll_follows_playback");
  GLADE_HOOKUP_OBJECT (mainwin, cursor_follows_playback, "cursor_follows_playback");
  GLADE_HOOKUP_OBJECT (mainwin, stop_after_current, "stop_after_current");
  GLADE_HOOKUP_OBJECT (mainwin, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (mainwin, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (mainwin, help1, "help1");
  GLADE_HOOKUP_OBJECT (mainwin, image319, "image319");
  GLADE_HOOKUP_OBJECT (mainwin, changelog1, "changelog1");
  GLADE_HOOKUP_OBJECT (mainwin, separator10, "separator10");
  GLADE_HOOKUP_OBJECT (mainwin, gpl1, "gpl1");
  GLADE_HOOKUP_OBJECT (mainwin, lgpl1, "lgpl1");
  GLADE_HOOKUP_OBJECT (mainwin, separator9, "separator9");
  GLADE_HOOKUP_OBJECT (mainwin, about1, "about1");
  GLADE_HOOKUP_OBJECT (mainwin, image320, "image320");
  GLADE_HOOKUP_OBJECT (mainwin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (mainwin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (mainwin, stopbtn, "stopbtn");
  GLADE_HOOKUP_OBJECT (mainwin, image128, "image128");
  GLADE_HOOKUP_OBJECT (mainwin, playbtn, "playbtn");
  GLADE_HOOKUP_OBJECT (mainwin, image2, "image2");
  GLADE_HOOKUP_OBJECT (mainwin, pausebtn, "pausebtn");
  GLADE_HOOKUP_OBJECT (mainwin, image3, "image3");
  GLADE_HOOKUP_OBJECT (mainwin, prevbtn, "prevbtn");
  GLADE_HOOKUP_OBJECT (mainwin, image4, "image4");
  GLADE_HOOKUP_OBJECT (mainwin, nextbtn, "nextbtn");
  GLADE_HOOKUP_OBJECT (mainwin, image5, "image5");
  GLADE_HOOKUP_OBJECT (mainwin, seekbar, "seekbar");
  GLADE_HOOKUP_OBJECT (mainwin, volumebar, "volumebar");
  GLADE_HOOKUP_OBJECT (mainwin, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (mainwin, table1, "table1");
  GLADE_HOOKUP_OBJECT (mainwin, _, "_");
  GLADE_HOOKUP_OBJECT (mainwin, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (mainwin, header, "header");
  GLADE_HOOKUP_OBJECT (mainwin, playlist, "playlist");
  GLADE_HOOKUP_OBJECT (mainwin, playscroll, "playscroll");
  GLADE_HOOKUP_OBJECT (mainwin, playhscroll, "playhscroll");
  GLADE_HOOKUP_OBJECT (mainwin, statusbar, "statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (mainwin), accel_group);

  return mainwin;
}

GtkWidget*
create_searchwin (void)
{
  GtkWidget *searchwin;
  GtkWidget *vbox4;
  GtkWidget *searchentry;
  GtkWidget *frame2;
  GtkWidget *table2;
  GtkWidget *searchscroll;
  GtkWidget *vbox5;
  GtkWidget *searchheader;
  GtkWidget *searchlist;
  GtkWidget *searchhscroll;

  searchwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (searchwin, 600, 150);
  gtk_widget_set_events (searchwin, GDK_KEY_PRESS_MASK);
  gtk_window_set_title (GTK_WINDOW (searchwin), "Search");
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (searchwin), TRUE);
  gtk_window_set_skip_pager_hint (GTK_WINDOW (searchwin), TRUE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (searchwin), vbox4);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 4);

  searchentry = gtk_entry_new ();
  gtk_widget_show (searchentry);
  gtk_box_pack_start (GTK_BOX (vbox4), searchentry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (searchentry), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (searchentry), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox4), frame2, TRUE, TRUE, 0);

  table2 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (frame2), table2);

  searchscroll = gtk_vscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 1, 0, 0)));
  gtk_widget_show (searchscroll);
  gtk_table_attach (GTK_TABLE (table2), searchscroll, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_table_attach (GTK_TABLE (table2), vbox5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  searchheader = gtk_drawing_area_new ();
  gtk_widget_show (searchheader);
  gtk_box_pack_start (GTK_BOX (vbox5), searchheader, FALSE, TRUE, 0);
  gtk_widget_set_size_request (searchheader, -1, 24);
  gtk_widget_set_events (searchheader, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  searchlist = gtk_drawing_area_new ();
  gtk_widget_show (searchlist);
  gtk_box_pack_start (GTK_BOX (vbox5), searchlist, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (searchlist, GTK_CAN_DEFAULT);
  gtk_widget_set_events (searchlist, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK);

  searchhscroll = gtk_hscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_show (searchhscroll);
  gtk_table_attach (GTK_TABLE (table2), searchhscroll, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  g_signal_connect ((gpointer) searchwin, "key_press_event",
                    G_CALLBACK (on_searchwin_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) searchwin, "delete_event",
                    G_CALLBACK (gtk_widget_hide_on_delete),
                    NULL);
  g_signal_connect ((gpointer) searchwin, "configure_event",
                    G_CALLBACK (on_searchwin_configure_event),
                    NULL);
  g_signal_connect ((gpointer) searchwin, "window_state_event",
                    G_CALLBACK (on_searchwin_window_state_event),
                    NULL);
  g_signal_connect ((gpointer) searchentry, "changed",
                    G_CALLBACK (on_searchentry_changed),
                    NULL);
  g_signal_connect ((gpointer) searchscroll, "value_changed",
                    G_CALLBACK (on_playscroll_value_changed),
                    NULL);
  g_signal_connect ((gpointer) searchheader, "button_press_event",
                    G_CALLBACK (on_header_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) searchheader, "button_release_event",
                    G_CALLBACK (on_header_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) searchheader, "configure_event",
                    G_CALLBACK (on_header_configure_event),
                    NULL);
  g_signal_connect ((gpointer) searchheader, "expose_event",
                    G_CALLBACK (on_header_expose_event),
                    NULL);
  g_signal_connect ((gpointer) searchheader, "motion_notify_event",
                    G_CALLBACK (on_header_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) searchlist, "button_press_event",
                    G_CALLBACK (on_playlist_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) searchlist, "configure_event",
                    G_CALLBACK (on_searchlist_configure_event),
                    NULL);
  g_signal_connect ((gpointer) searchlist, "expose_event",
                    G_CALLBACK (on_playlist_expose_event),
                    NULL);
  g_signal_connect ((gpointer) searchlist, "scroll_event",
                    G_CALLBACK (on_playlist_scroll_event),
                    NULL);
  g_signal_connect ((gpointer) searchlist, "realize",
                    G_CALLBACK (on_searchlist_realize),
                    NULL);
  g_signal_connect ((gpointer) searchlist, "button_release_event",
                    G_CALLBACK (on_playlist_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) searchlist, "motion_notify_event",
                    G_CALLBACK (on_playlist_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) searchhscroll, "value_changed",
                    G_CALLBACK (on_searchhscroll_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (searchwin, searchwin, "searchwin");
  GLADE_HOOKUP_OBJECT (searchwin, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (searchwin, searchentry, "searchentry");
  GLADE_HOOKUP_OBJECT (searchwin, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (searchwin, table2, "table2");
  GLADE_HOOKUP_OBJECT (searchwin, searchscroll, "searchscroll");
  GLADE_HOOKUP_OBJECT (searchwin, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (searchwin, searchheader, "searchheader");
  GLADE_HOOKUP_OBJECT (searchwin, searchlist, "searchlist");
  GLADE_HOOKUP_OBJECT (searchwin, searchhscroll, "searchhscroll");

  gtk_widget_grab_default (searchlist);
  return searchwin;
}

GtkWidget*
create_traymenu (void)
{
  GtkWidget *traymenu;
  GtkWidget *stop2;
  GtkWidget *image59;
  GtkWidget *play2;
  GtkWidget *image60;
  GtkWidget *pause2;
  GtkWidget *image61;
  GtkWidget *previous2;
  GtkWidget *image62;
  GtkWidget *next2;
  GtkWidget *image63;
  GtkWidget *play_random1;
  GtkWidget *separator4;
  GtkWidget *about3;
  GtkWidget *image64;
  GtkWidget *separator3;
  GtkWidget *quit;
  GtkWidget *image65;

  traymenu = gtk_menu_new ();

  stop2 = gtk_image_menu_item_new_with_mnemonic ("Stop");
  gtk_widget_show (stop2);
  gtk_container_add (GTK_CONTAINER (traymenu), stop2);

  image59 = gtk_image_new_from_stock ("gtk-media-stop", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image59);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (stop2), image59);

  play2 = gtk_image_menu_item_new_with_mnemonic ("Play");
  gtk_widget_show (play2);
  gtk_container_add (GTK_CONTAINER (traymenu), play2);

  image60 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image60);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (play2), image60);

  pause2 = gtk_image_menu_item_new_with_mnemonic ("Pause");
  gtk_widget_show (pause2);
  gtk_container_add (GTK_CONTAINER (traymenu), pause2);

  image61 = gtk_image_new_from_stock ("gtk-media-pause", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image61);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (pause2), image61);

  previous2 = gtk_image_menu_item_new_with_mnemonic ("Previous");
  gtk_widget_show (previous2);
  gtk_container_add (GTK_CONTAINER (traymenu), previous2);

  image62 = gtk_image_new_from_stock ("gtk-media-previous", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image62);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (previous2), image62);

  next2 = gtk_image_menu_item_new_with_mnemonic ("Next");
  gtk_widget_show (next2);
  gtk_container_add (GTK_CONTAINER (traymenu), next2);

  image63 = gtk_image_new_from_stock ("gtk-media-next", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image63);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (next2), image63);

  play_random1 = gtk_menu_item_new_with_mnemonic ("Play Random");
  gtk_widget_show (play_random1);
  gtk_container_add (GTK_CONTAINER (traymenu), play_random1);

  separator4 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (traymenu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  about3 = gtk_image_menu_item_new_with_mnemonic ("About");
  gtk_widget_show (about3);
  gtk_container_add (GTK_CONTAINER (traymenu), about3);

  image64 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image64);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about3), image64);

  separator3 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (traymenu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  quit = gtk_image_menu_item_new_with_mnemonic ("Quit");
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (traymenu), quit);

  image65 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image65);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit), image65);

  g_signal_connect ((gpointer) stop2, "activate",
                    G_CALLBACK (on_stopbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) play2, "activate",
                    G_CALLBACK (on_playbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) pause2, "activate",
                    G_CALLBACK (on_pausebtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) previous2, "activate",
                    G_CALLBACK (on_prevbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) next2, "activate",
                    G_CALLBACK (on_nextbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) play_random1, "activate",
                    G_CALLBACK (on_playrand_clicked),
                    NULL);
  g_signal_connect ((gpointer) about3, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (traymenu, traymenu, "traymenu");
  GLADE_HOOKUP_OBJECT (traymenu, stop2, "stop2");
  GLADE_HOOKUP_OBJECT (traymenu, image59, "image59");
  GLADE_HOOKUP_OBJECT (traymenu, play2, "play2");
  GLADE_HOOKUP_OBJECT (traymenu, image60, "image60");
  GLADE_HOOKUP_OBJECT (traymenu, pause2, "pause2");
  GLADE_HOOKUP_OBJECT (traymenu, image61, "image61");
  GLADE_HOOKUP_OBJECT (traymenu, previous2, "previous2");
  GLADE_HOOKUP_OBJECT (traymenu, image62, "image62");
  GLADE_HOOKUP_OBJECT (traymenu, next2, "next2");
  GLADE_HOOKUP_OBJECT (traymenu, image63, "image63");
  GLADE_HOOKUP_OBJECT (traymenu, play_random1, "play_random1");
  GLADE_HOOKUP_OBJECT (traymenu, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (traymenu, about3, "about3");
  GLADE_HOOKUP_OBJECT (traymenu, image64, "image64");
  GLADE_HOOKUP_OBJECT (traymenu, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (traymenu, quit, "quit");
  GLADE_HOOKUP_OBJECT (traymenu, image65, "image65");

  return traymenu;
}

GtkWidget*
create_addprogress (void)
{
  GtkWidget *addprogress;
  GtkWidget *vbox6;
  GtkWidget *progresstitle;
  GtkWidget *hbox7;
  GtkWidget *label22;
  GtkWidget *button1;

  addprogress = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (addprogress), 12);
  gtk_window_set_title (GTK_WINDOW (addprogress), "Adding files...");
  gtk_window_set_position (GTK_WINDOW (addprogress), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_modal (GTK_WINDOW (addprogress), TRUE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (addprogress), TRUE);
  gtk_window_set_skip_pager_hint (GTK_WINDOW (addprogress), TRUE);

  vbox6 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (addprogress), vbox6);

  progresstitle = gtk_entry_new ();
  gtk_widget_show (progresstitle);
  gtk_box_pack_start (GTK_BOX (vbox6), progresstitle, TRUE, FALSE, 0);
  gtk_widget_set_size_request (progresstitle, 500, -1);
  GTK_WIDGET_UNSET_FLAGS (progresstitle, GTK_CAN_FOCUS);
  gtk_editable_set_editable (GTK_EDITABLE (progresstitle), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (progresstitle), 8226);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox7, FALSE, TRUE, 2);

  label22 = gtk_label_new ("");
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox7), label22, TRUE, FALSE, 0);

  button1 = gtk_button_new_with_mnemonic ("Abort");
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox7), button1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (button1, 83, -1);
  GTK_WIDGET_UNSET_FLAGS (button1, GTK_CAN_FOCUS);

  g_signal_connect ((gpointer) addprogress, "delete_event",
                    G_CALLBACK (on_addprogress_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_progress_abort),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (addprogress, addprogress, "addprogress");
  GLADE_HOOKUP_OBJECT (addprogress, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (addprogress, progresstitle, "progresstitle");
  GLADE_HOOKUP_OBJECT (addprogress, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (addprogress, label22, "label22");
  GLADE_HOOKUP_OBJECT (addprogress, button1, "button1");

  return addprogress;
}

GtkWidget*
create_helpwindow (void)
{
  GtkWidget *helpwindow;
  GtkWidget *scrolledwindow1;
  GtkWidget *helptext;

  helpwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (helpwindow, 600, 400);
  gtk_widget_set_events (helpwindow, GDK_KEY_PRESS_MASK);
  gtk_window_set_title (GTK_WINDOW (helpwindow), "Help");
  gtk_window_set_modal (GTK_WINDOW (helpwindow), TRUE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (helpwindow), TRUE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (helpwindow), TRUE);
  gtk_window_set_skip_pager_hint (GTK_WINDOW (helpwindow), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (helpwindow), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  helptext = gtk_text_view_new ();
  gtk_widget_show (helptext);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), helptext);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (helptext), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (helptext), GTK_WRAP_WORD);
  gtk_text_view_set_left_margin (GTK_TEXT_VIEW (helptext), 10);
  gtk_text_view_set_right_margin (GTK_TEXT_VIEW (helptext), 10);

  g_signal_connect ((gpointer) helpwindow, "key_press_event",
                    G_CALLBACK (on_helpwindow_key_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (helpwindow, helpwindow, "helpwindow");
  GLADE_HOOKUP_OBJECT (helpwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (helpwindow, helptext, "helptext");

  return helpwindow;
}

GtkWidget*
create_prefwin (void)
{
  GtkWidget *prefwin;
  GtkWidget *pref_vbox;
  GtkWidget *notebook2;
  GtkWidget *vbox10;
  GtkWidget *hbox11;
  GtkWidget *label23;
  GtkWidget *pref_output_plugin;
  GtkWidget *hbox12;
  GtkWidget *label4;
  GtkWidget *pref_soundcard;
  GtkWidget *Sound;
  GtkWidget *vbox8;
  GtkWidget *pref_dynsamplerate;
  GtkWidget *hbox9;
  GtkWidget *label6;
  GtkWidget *pref_src_quality;
  GtkWidget *hbox10;
  GtkWidget *label8;
  GtkWidget *pref_replaygain_mode;
  GtkWidget *pref_replaygain_scale;
  GtkWidget *label39;
  GtkWidget *vbox9;
  GtkWidget *pref_close_send_to_tray;
  GtkWidget *label2;
  GtkWidget *vbox11;
  GtkWidget *pref_network_enableproxy;
  GtkWidget *hbox13;
  GtkWidget *label18;
  GtkWidget *pref_network_proxyaddress;
  GtkWidget *hbox14;
  GtkWidget *label19;
  GtkWidget *pref_network_proxyport;
  GtkWidget *hbox15;
  GtkWidget *label20;
  GtkWidget *pref_network_proxytype;
  GtkWidget *label16;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow2;
  GtkWidget *pref_pluginlist;
  GtkWidget *vbox12;
  GtkWidget *hbox16;
  GtkWidget *label11;
  GtkWidget *pref_plugin_descr;
  GtkWidget *hbox17;
  GtkWidget *label12;
  GtkWidget *pref_plugin_author;
  GtkWidget *hbox18;
  GtkWidget *label13;
  GtkWidget *pref_plugin_email;
  GtkWidget *hbox19;
  GtkWidget *label14;
  GtkWidget *pref_plugin_website;
  GtkWidget *hbox20;
  GtkWidget *configure_plugin;
  GtkWidget *label3;
  GtkWidget *hbox21;
  GtkWidget *filler;
  GtkWidget *pref_close;
  GtkWidget *alignment1;
  GtkWidget *hbox22;
  GtkWidget *image321;
  GtkWidget *label40;

  prefwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (prefwin, 642, 372);
  gtk_container_set_border_width (GTK_CONTAINER (prefwin), 12);
  gtk_window_set_title (GTK_WINDOW (prefwin), "Preferences");
  gtk_window_set_modal (GTK_WINDOW (prefwin), TRUE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (prefwin), TRUE);
  gtk_window_set_skip_pager_hint (GTK_WINDOW (prefwin), TRUE);

  pref_vbox = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (pref_vbox);
  gtk_container_add (GTK_CONTAINER (prefwin), pref_vbox);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (pref_vbox), notebook2, TRUE, TRUE, 0);

  vbox10 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (notebook2), vbox10);
  gtk_container_set_border_width (GTK_CONTAINER (vbox10), 12);

  hbox11 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox11, FALSE, FALSE, 0);

  label23 = gtk_label_new ("Output plugin:");
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  pref_output_plugin = gtk_combo_box_new_text ();
  gtk_widget_show (pref_output_plugin);
  gtk_box_pack_start (GTK_BOX (hbox11), pref_output_plugin, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox12, FALSE, FALSE, 0);

  label4 = gtk_label_new ("Output device:");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox12), label4, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  pref_soundcard = gtk_combo_box_new_text ();
  gtk_widget_show (pref_soundcard);
  gtk_box_pack_start (GTK_BOX (hbox12), pref_soundcard, TRUE, TRUE, 0);

  Sound = gtk_label_new ("Sound");
  gtk_widget_show (Sound);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), Sound);

  vbox8 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (notebook2), vbox8);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 12);

  pref_dynsamplerate = gtk_check_button_new_with_mnemonic ("Allow dynamic samplerate switching");
  gtk_widget_show (pref_dynsamplerate);
  gtk_box_pack_start (GTK_BOX (vbox8), pref_dynsamplerate, FALSE, FALSE, 0);

  hbox9 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox9, FALSE, FALSE, 0);

  label6 = gtk_label_new ("Samplerate conversion quality:");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox9), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  pref_src_quality = gtk_combo_box_new_text ();
  gtk_widget_show (pref_src_quality);
  gtk_box_pack_start (GTK_BOX (hbox9), pref_src_quality, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_src_quality), "sinc_best_quality");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_src_quality), "sinc_medium_quality");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_src_quality), "sinc_fastest");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_src_quality), "sinc_zero_order_hold");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_src_quality), "linear");

  hbox10 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox10, FALSE, FALSE, 0);

  label8 = gtk_label_new ("Replaygain mode:");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox10), label8, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  pref_replaygain_mode = gtk_combo_box_new_text ();
  gtk_widget_show (pref_replaygain_mode);
  gtk_box_pack_start (GTK_BOX (hbox10), pref_replaygain_mode, TRUE, TRUE, 0);
  gtk_widget_set_size_request (pref_replaygain_mode, 337, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_replaygain_mode), "Disable");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_replaygain_mode), "Track");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_replaygain_mode), "Album");

  pref_replaygain_scale = gtk_check_button_new_with_mnemonic ("Replaygain peak scale");
  gtk_widget_show (pref_replaygain_scale);
  gtk_box_pack_start (GTK_BOX (vbox8), pref_replaygain_scale, FALSE, FALSE, 0);

  label39 = gtk_label_new ("Sound (adv.)");
  gtk_widget_show (label39);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label39);

  vbox9 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (notebook2), vbox9);
  gtk_container_set_border_width (GTK_CONTAINER (vbox9), 12);

  pref_close_send_to_tray = gtk_check_button_new_with_mnemonic ("Close minimizes to tray");
  gtk_widget_show (pref_close_send_to_tray);
  gtk_box_pack_start (GTK_BOX (vbox9), pref_close_send_to_tray, FALSE, FALSE, 0);

  label2 = gtk_label_new ("GUI");
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label2);

  vbox11 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (notebook2), vbox11);
  gtk_container_set_border_width (GTK_CONTAINER (vbox11), 12);

  pref_network_enableproxy = gtk_check_button_new_with_mnemonic ("Enable proxy server");
  gtk_widget_show (pref_network_enableproxy);
  gtk_box_pack_start (GTK_BOX (vbox11), pref_network_enableproxy, FALSE, FALSE, 0);

  hbox13 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox13, FALSE, FALSE, 0);

  label18 = gtk_label_new ("Proxy server address:");
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox13), label18, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  pref_network_proxyaddress = gtk_entry_new ();
  gtk_widget_show (pref_network_proxyaddress);
  gtk_box_pack_start (GTK_BOX (hbox13), pref_network_proxyaddress, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (pref_network_proxyaddress), 8226);

  hbox14 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox14, FALSE, FALSE, 0);

  label19 = gtk_label_new ("Proxy server port:");
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox14), label19, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  pref_network_proxyport = gtk_entry_new ();
  gtk_widget_show (pref_network_proxyport);
  gtk_box_pack_start (GTK_BOX (hbox14), pref_network_proxyport, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (pref_network_proxyport), 8226);

  hbox15 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox15, FALSE, FALSE, 0);

  label20 = gtk_label_new ("Proxy type:");
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox15), label20, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  pref_network_proxytype = gtk_combo_box_new_text ();
  gtk_widget_show (pref_network_proxytype);
  gtk_box_pack_start (GTK_BOX (hbox15), pref_network_proxytype, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_network_proxytype), "HTTP");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_network_proxytype), "HTTP_1_0");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_network_proxytype), "SOCKS4");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_network_proxytype), "SOCKS5");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_network_proxytype), "SOCKS4A");
  gtk_combo_box_append_text (GTK_COMBO_BOX (pref_network_proxytype), "SOCKS5_HOSTNAME");

  label16 = gtk_label_new ("Network");
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label16);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_container_add (GTK_CONTAINER (notebook2), hpaned1);
  gtk_container_set_border_width (GTK_CONTAINER (hpaned1), 12);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow2, FALSE, FALSE);
  gtk_widget_set_size_request (scrolledwindow2, 280, -1);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow2), 3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  pref_pluginlist = gtk_tree_view_new ();
  gtk_widget_show (pref_pluginlist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), pref_pluginlist);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (pref_pluginlist), TRUE);

  vbox12 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox12);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vbox12, TRUE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (vbox12), 12);

  hbox16 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox16, FALSE, FALSE, 0);

  label11 = gtk_label_new ("Description:");
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox16), label11, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  pref_plugin_descr = gtk_entry_new ();
  gtk_widget_show (pref_plugin_descr);
  gtk_box_pack_start (GTK_BOX (hbox16), pref_plugin_descr, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pref_plugin_descr), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (pref_plugin_descr), 9679);

  hbox17 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox17, FALSE, FALSE, 0);

  label12 = gtk_label_new ("Author(s):");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox17), label12, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  pref_plugin_author = gtk_entry_new ();
  gtk_widget_show (pref_plugin_author);
  gtk_box_pack_start (GTK_BOX (hbox17), pref_plugin_author, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pref_plugin_author), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (pref_plugin_author), 9679);

  hbox18 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox18, FALSE, FALSE, 0);

  label13 = gtk_label_new ("Email:");
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox18), label13, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  pref_plugin_email = gtk_entry_new ();
  gtk_widget_show (pref_plugin_email);
  gtk_box_pack_start (GTK_BOX (hbox18), pref_plugin_email, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pref_plugin_email), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (pref_plugin_email), 9679);

  hbox19 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox19, FALSE, FALSE, 0);

  label14 = gtk_label_new ("Website:");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox19), label14, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  pref_plugin_website = gtk_entry_new ();
  gtk_widget_show (pref_plugin_website);
  gtk_box_pack_start (GTK_BOX (hbox19), pref_plugin_website, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (pref_plugin_website), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (pref_plugin_website), 9679);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox20, FALSE, FALSE, 0);

  configure_plugin = gtk_button_new_with_mnemonic ("Configure");
  gtk_widget_show (configure_plugin);
  gtk_box_pack_start (GTK_BOX (hbox20), configure_plugin, TRUE, FALSE, 0);

  label3 = gtk_label_new ("Plugins");
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 4), label3);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (pref_vbox), hbox21, FALSE, TRUE, 0);

  filler = gtk_label_new ("");
  gtk_widget_show (filler);
  gtk_box_pack_start (GTK_BOX (hbox21), filler, TRUE, TRUE, 0);

  pref_close = gtk_button_new ();
  gtk_widget_show (pref_close);
  gtk_box_pack_start (GTK_BOX (hbox21), pref_close, FALSE, FALSE, 0);
  gtk_widget_set_size_request (pref_close, 76, -1);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (pref_close), alignment1);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox22);

  image321 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image321);
  gtk_box_pack_start (GTK_BOX (hbox22), image321, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic ("Close");
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox22), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) prefwin, "key_press_event",
                    G_CALLBACK (on_prefwin_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) prefwin, "delete_event",
                    G_CALLBACK (on_prefwin_delete_event),
                    NULL);
  g_signal_connect ((gpointer) pref_dynsamplerate, "clicked",
                    G_CALLBACK (on_pref_dynsamplerate_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_src_quality, "changed",
                    G_CALLBACK (on_pref_src_quality_changed),
                    NULL);
  g_signal_connect ((gpointer) pref_replaygain_mode, "changed",
                    G_CALLBACK (on_pref_replaygain_mode_changed),
                    NULL);
  g_signal_connect ((gpointer) pref_replaygain_scale, "clicked",
                    G_CALLBACK (on_pref_replaygain_scale_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_close_send_to_tray, "clicked",
                    G_CALLBACK (on_pref_close_send_to_tray_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_network_enableproxy, "clicked",
                    G_CALLBACK (on_pref_network_enableproxy_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_network_proxyaddress, "changed",
                    G_CALLBACK (on_pref_network_proxyaddress_changed),
                    NULL);
  g_signal_connect ((gpointer) pref_network_proxyport, "changed",
                    G_CALLBACK (on_pref_network_proxyport_changed),
                    NULL);
  g_signal_connect ((gpointer) pref_network_proxytype, "changed",
                    G_CALLBACK (on_pref_network_proxytype_changed),
                    NULL);
  g_signal_connect ((gpointer) pref_pluginlist, "cursor_changed",
                    G_CALLBACK (on_pref_pluginlist_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) configure_plugin, "clicked",
                    G_CALLBACK (on_configure_plugin_clicked),
                    NULL);
  g_signal_connect ((gpointer) pref_close, "clicked",
                    G_CALLBACK (on_pref_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefwin, prefwin, "prefwin");
  GLADE_HOOKUP_OBJECT (prefwin, pref_vbox, "pref_vbox");
  GLADE_HOOKUP_OBJECT (prefwin, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (prefwin, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (prefwin, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (prefwin, label23, "label23");
  GLADE_HOOKUP_OBJECT (prefwin, pref_output_plugin, "pref_output_plugin");
  GLADE_HOOKUP_OBJECT (prefwin, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (prefwin, label4, "label4");
  GLADE_HOOKUP_OBJECT (prefwin, pref_soundcard, "pref_soundcard");
  GLADE_HOOKUP_OBJECT (prefwin, Sound, "Sound");
  GLADE_HOOKUP_OBJECT (prefwin, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (prefwin, pref_dynsamplerate, "pref_dynsamplerate");
  GLADE_HOOKUP_OBJECT (prefwin, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (prefwin, label6, "label6");
  GLADE_HOOKUP_OBJECT (prefwin, pref_src_quality, "pref_src_quality");
  GLADE_HOOKUP_OBJECT (prefwin, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (prefwin, label8, "label8");
  GLADE_HOOKUP_OBJECT (prefwin, pref_replaygain_mode, "pref_replaygain_mode");
  GLADE_HOOKUP_OBJECT (prefwin, pref_replaygain_scale, "pref_replaygain_scale");
  GLADE_HOOKUP_OBJECT (prefwin, label39, "label39");
  GLADE_HOOKUP_OBJECT (prefwin, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (prefwin, pref_close_send_to_tray, "pref_close_send_to_tray");
  GLADE_HOOKUP_OBJECT (prefwin, label2, "label2");
  GLADE_HOOKUP_OBJECT (prefwin, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (prefwin, pref_network_enableproxy, "pref_network_enableproxy");
  GLADE_HOOKUP_OBJECT (prefwin, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (prefwin, label18, "label18");
  GLADE_HOOKUP_OBJECT (prefwin, pref_network_proxyaddress, "pref_network_proxyaddress");
  GLADE_HOOKUP_OBJECT (prefwin, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (prefwin, label19, "label19");
  GLADE_HOOKUP_OBJECT (prefwin, pref_network_proxyport, "pref_network_proxyport");
  GLADE_HOOKUP_OBJECT (prefwin, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (prefwin, label20, "label20");
  GLADE_HOOKUP_OBJECT (prefwin, pref_network_proxytype, "pref_network_proxytype");
  GLADE_HOOKUP_OBJECT (prefwin, label16, "label16");
  GLADE_HOOKUP_OBJECT (prefwin, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (prefwin, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (prefwin, pref_pluginlist, "pref_pluginlist");
  GLADE_HOOKUP_OBJECT (prefwin, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (prefwin, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (prefwin, label11, "label11");
  GLADE_HOOKUP_OBJECT (prefwin, pref_plugin_descr, "pref_plugin_descr");
  GLADE_HOOKUP_OBJECT (prefwin, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (prefwin, label12, "label12");
  GLADE_HOOKUP_OBJECT (prefwin, pref_plugin_author, "pref_plugin_author");
  GLADE_HOOKUP_OBJECT (prefwin, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (prefwin, label13, "label13");
  GLADE_HOOKUP_OBJECT (prefwin, pref_plugin_email, "pref_plugin_email");
  GLADE_HOOKUP_OBJECT (prefwin, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (prefwin, label14, "label14");
  GLADE_HOOKUP_OBJECT (prefwin, pref_plugin_website, "pref_plugin_website");
  GLADE_HOOKUP_OBJECT (prefwin, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (prefwin, configure_plugin, "configure_plugin");
  GLADE_HOOKUP_OBJECT (prefwin, label3, "label3");
  GLADE_HOOKUP_OBJECT (prefwin, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (prefwin, filler, "filler");
  GLADE_HOOKUP_OBJECT (prefwin, pref_close, "pref_close");
  GLADE_HOOKUP_OBJECT (prefwin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (prefwin, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (prefwin, image321, "image321");
  GLADE_HOOKUP_OBJECT (prefwin, label40, "label40");

  return prefwin;
}

GtkWidget*
create_headermenu (void)
{
  GtkWidget *headermenu;
  GtkWidget *add_column;
  GtkWidget *edit_column;
  GtkWidget *remove_column;

  headermenu = gtk_menu_new ();

  add_column = gtk_menu_item_new_with_mnemonic ("Add column");
  gtk_widget_show (add_column);
  gtk_container_add (GTK_CONTAINER (headermenu), add_column);

  edit_column = gtk_menu_item_new_with_mnemonic ("Edit column");
  gtk_widget_show (edit_column);
  gtk_container_add (GTK_CONTAINER (headermenu), edit_column);

  remove_column = gtk_menu_item_new_with_mnemonic ("Remove column");
  gtk_widget_show (remove_column);
  gtk_container_add (GTK_CONTAINER (headermenu), remove_column);

  g_signal_connect ((gpointer) add_column, "activate",
                    G_CALLBACK (on_add_column_activate),
                    NULL);
  g_signal_connect ((gpointer) edit_column, "activate",
                    G_CALLBACK (on_edit_column_activate),
                    NULL);
  g_signal_connect ((gpointer) remove_column, "activate",
                    G_CALLBACK (on_remove_column_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (headermenu, headermenu, "headermenu");
  GLADE_HOOKUP_OBJECT (headermenu, add_column, "add_column");
  GLADE_HOOKUP_OBJECT (headermenu, edit_column, "edit_column");
  GLADE_HOOKUP_OBJECT (headermenu, remove_column, "remove_column");

  return headermenu;
}

GtkWidget*
create_addlocation (void)
{
  GtkWidget *addlocation;
  GtkWidget *vbox7;
  GtkWidget *addlocation_entry;
  GtkWidget *hbox8;
  GtkWidget *label21;
  GtkWidget *addlocation_ok;

  addlocation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (addlocation), 12);
  gtk_window_set_title (GTK_WINDOW (addlocation), "Add Location");
  gtk_window_set_modal (GTK_WINDOW (addlocation), TRUE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (addlocation), TRUE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (addlocation), TRUE);
  gtk_window_set_skip_pager_hint (GTK_WINDOW (addlocation), TRUE);

  vbox7 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (addlocation), vbox7);

  addlocation_entry = gtk_entry_new ();
  gtk_widget_show (addlocation_entry);
  gtk_box_pack_start (GTK_BOX (vbox7), addlocation_entry, FALSE, FALSE, 0);
  gtk_widget_set_size_request (addlocation_entry, 346, -1);
  gtk_entry_set_invisible_char (GTK_ENTRY (addlocation_entry), 8226);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox8, FALSE, TRUE, 2);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox8), label21, TRUE, FALSE, 0);

  addlocation_ok = gtk_button_new_with_mnemonic ("OK");
  gtk_widget_show (addlocation_ok);
  gtk_box_pack_start (GTK_BOX (hbox8), addlocation_ok, FALSE, FALSE, 0);
  gtk_widget_set_size_request (addlocation_ok, 83, -1);
  GTK_WIDGET_UNSET_FLAGS (addlocation_ok, GTK_CAN_FOCUS);

  g_signal_connect ((gpointer) addlocation, "key_press_event",
                    G_CALLBACK (on_addlocation_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) addlocation_entry, "activate",
                    G_CALLBACK (on_addlocation_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) addlocation_ok, "clicked",
                    G_CALLBACK (on_addlocation_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (addlocation, addlocation, "addlocation");
  GLADE_HOOKUP_OBJECT (addlocation, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (addlocation, addlocation_entry, "addlocation_entry");
  GLADE_HOOKUP_OBJECT (addlocation, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (addlocation, label21, "label21");
  GLADE_HOOKUP_OBJECT (addlocation, addlocation_ok, "addlocation_ok");

  return addlocation;
}

GtkWidget*
create_trackproperties (void)
{
  GtkWidget *trackproperties;
  GtkWidget *vbox13;
  GtkWidget *hbox23;
  GtkWidget *label27;
  GtkWidget *location;
  GtkWidget *hbox24;
  GtkWidget *label28;
  GtkWidget *title;
  GtkWidget *hbox25;
  GtkWidget *label29;
  GtkWidget *artist;
  GtkWidget *hbox26;
  GtkWidget *label30;
  GtkWidget *album;
  GtkWidget *hbox27;
  GtkWidget *label35;
  GtkWidget *genre;
  GtkWidget *table8;
  GtkWidget *label31;
  GtkWidget *label33;
  GtkWidget *year;
  GtkWidget *track;
  GtkWidget *hbox28;
  GtkWidget *label36;
  GtkWidget *scrolledwindow4;
  GtkWidget *comment;

  trackproperties = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (trackproperties), "Track Properties");
  gtk_window_set_destroy_with_parent (GTK_WINDOW (trackproperties), TRUE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (trackproperties), TRUE);
  gtk_window_set_skip_pager_hint (GTK_WINDOW (trackproperties), TRUE);

  vbox13 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (trackproperties), vbox13);
  gtk_container_set_border_width (GTK_CONTAINER (vbox13), 12);

  hbox23 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox23);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox23, FALSE, FALSE, 0);

  label27 = gtk_label_new ("Location:");
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox23), label27, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  location = gtk_entry_new ();
  gtk_widget_show (location);
  gtk_box_pack_start (GTK_BOX (hbox23), location, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (location), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (location), 8226);

  hbox24 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox24);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox24, FALSE, FALSE, 0);

  label28 = gtk_label_new ("Title:");
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox24), label28, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  title = gtk_entry_new ();
  gtk_widget_show (title);
  gtk_box_pack_start (GTK_BOX (hbox24), title, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (title), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (title), 8226);

  hbox25 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox25);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox25, FALSE, FALSE, 0);

  label29 = gtk_label_new ("Artist:");
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox25), label29, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  artist = gtk_entry_new ();
  gtk_widget_show (artist);
  gtk_box_pack_start (GTK_BOX (hbox25), artist, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (artist), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (artist), 8226);

  hbox26 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox26);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox26, FALSE, FALSE, 0);

  label30 = gtk_label_new ("Album:");
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox26), label30, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  album = gtk_entry_new ();
  gtk_widget_show (album);
  gtk_box_pack_start (GTK_BOX (hbox26), album, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (album), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (album), 8226);

  hbox27 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox27);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox27, FALSE, FALSE, 0);

  label35 = gtk_label_new ("Genre:");
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox27), label35, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  genre = gtk_entry_new ();
  gtk_widget_show (genre);
  gtk_box_pack_start (GTK_BOX (hbox27), genre, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (genre), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (genre), 8226);

  table8 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table8);
  gtk_box_pack_start (GTK_BOX (vbox13), table8, FALSE, FALSE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 8);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 8);

  label31 = gtk_label_new ("Year:");
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table8), label31, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label31), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  label33 = gtk_label_new ("Track:");
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table8), label33, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  year = gtk_entry_new ();
  gtk_widget_show (year);
  gtk_table_attach (GTK_TABLE (table8), year, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (year), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (year), 8226);

  track = gtk_entry_new ();
  gtk_widget_show (track);
  gtk_table_attach (GTK_TABLE (table8), track, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (track), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (track), 8226);

  hbox28 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox28);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox28, TRUE, TRUE, 0);

  label36 = gtk_label_new ("Comment:");
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox28), label36, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (hbox28), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  comment = gtk_text_view_new ();
  gtk_widget_show (comment);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), comment);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (comment), FALSE);

  g_signal_connect ((gpointer) trackproperties, "key_press_event",
                    G_CALLBACK (on_trackproperties_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) trackproperties, "delete_event",
                    G_CALLBACK (on_trackproperties_delete_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (trackproperties, trackproperties, "trackproperties");
  GLADE_HOOKUP_OBJECT (trackproperties, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (trackproperties, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (trackproperties, label27, "label27");
  GLADE_HOOKUP_OBJECT (trackproperties, location, "location");
  GLADE_HOOKUP_OBJECT (trackproperties, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (trackproperties, label28, "label28");
  GLADE_HOOKUP_OBJECT (trackproperties, title, "title");
  GLADE_HOOKUP_OBJECT (trackproperties, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (trackproperties, label29, "label29");
  GLADE_HOOKUP_OBJECT (trackproperties, artist, "artist");
  GLADE_HOOKUP_OBJECT (trackproperties, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (trackproperties, label30, "label30");
  GLADE_HOOKUP_OBJECT (trackproperties, album, "album");
  GLADE_HOOKUP_OBJECT (trackproperties, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (trackproperties, label35, "label35");
  GLADE_HOOKUP_OBJECT (trackproperties, genre, "genre");
  GLADE_HOOKUP_OBJECT (trackproperties, table8, "table8");
  GLADE_HOOKUP_OBJECT (trackproperties, label31, "label31");
  GLADE_HOOKUP_OBJECT (trackproperties, label33, "label33");
  GLADE_HOOKUP_OBJECT (trackproperties, year, "year");
  GLADE_HOOKUP_OBJECT (trackproperties, track, "track");
  GLADE_HOOKUP_OBJECT (trackproperties, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (trackproperties, label36, "label36");
  GLADE_HOOKUP_OBJECT (trackproperties, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (trackproperties, comment, "comment");

  return trackproperties;
}

GtkWidget*
create_editcolumndlg (void)
{
  GtkWidget *editcolumndlg;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox14;
  GtkWidget *hbox29;
  GtkWidget *label26;
  GtkWidget *title;
  GtkWidget *hbox30;
  GtkWidget *label37;
  GtkWidget *id;
  GtkWidget *hbox31;
  GtkWidget *fmtlabel;
  GtkWidget *format;
  GtkWidget *hbox32;
  GtkWidget *label38;
  GtkWidget *align;
  GtkWidget *label25;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  editcolumndlg = gtk_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (editcolumndlg), 12);
  gtk_window_set_title (GTK_WINDOW (editcolumndlg), "dialog1");
  gtk_window_set_modal (GTK_WINDOW (editcolumndlg), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (editcolumndlg), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (editcolumndlg)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox14 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox14, TRUE, TRUE, 0);

  hbox29 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox29);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox29, FALSE, FALSE, 0);

  label26 = gtk_label_new ("Title:");
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox29), label26, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  title = gtk_entry_new ();
  gtk_widget_show (title);
  gtk_box_pack_start (GTK_BOX (hbox29), title, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (title), "Enter new column title here");
  gtk_entry_set_invisible_char (GTK_ENTRY (title), 9679);
  gtk_entry_set_activates_default (GTK_ENTRY (title), TRUE);

  hbox30 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox30);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox30, FALSE, FALSE, 0);

  label37 = gtk_label_new ("Type:");
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox30), label37, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  id = gtk_combo_box_new_text ();
  gtk_widget_show (id);
  gtk_box_pack_start (GTK_BOX (hbox30), id, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "File number");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Playing");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Artist - Album");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Artist");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Album");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Title");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Length");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Track");
  gtk_combo_box_append_text (GTK_COMBO_BOX (id), "Custom");

  hbox31 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox31);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox31, FALSE, FALSE, 0);

  fmtlabel = gtk_label_new ("Format:");
  gtk_widget_show (fmtlabel);
  gtk_box_pack_start (GTK_BOX (hbox31), fmtlabel, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (fmtlabel), 0, 0.5);

  format = gtk_entry_new ();
  gtk_widget_show (format);
  gtk_box_pack_start (GTK_BOX (hbox31), format, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (format), 9679);
  gtk_entry_set_activates_default (GTK_ENTRY (format), TRUE);

  hbox32 = gtk_hbox_new (FALSE, 8);
  gtk_widget_show (hbox32);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox32, FALSE, FALSE, 0);

  label38 = gtk_label_new ("Alignment:");
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox32), label38, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  align = gtk_combo_box_new_text ();
  gtk_widget_show (align);
  gtk_box_pack_start (GTK_BOX (hbox32), align, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (align), "Left");
  gtk_combo_box_append_text (GTK_COMBO_BOX (align), "Right");

  label25 = gtk_label_new ("Format conversions (start with %):\n  [a]rtist, [t]itle, al[b]um, track[n]umber,\n  [l]ength, [y]ear, [g]enre, [c]omment,\n  copy[r]ight, [f]ilename\nExample: %a - %t [%l]");
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (vbox14), label25, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label25, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label25), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label25), 0.1, 0.5);

  dialog_action_area1 = GTK_DIALOG (editcolumndlg)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_with_mnemonic ("_Cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (editcolumndlg), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_with_mnemonic ("_OK");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (editcolumndlg), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) id, "changed",
                    G_CALLBACK (on_column_id_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (editcolumndlg, editcolumndlg, "editcolumndlg");
  GLADE_HOOKUP_OBJECT_NO_REF (editcolumndlg, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (editcolumndlg, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (editcolumndlg, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (editcolumndlg, label26, "label26");
  GLADE_HOOKUP_OBJECT (editcolumndlg, title, "title");
  GLADE_HOOKUP_OBJECT (editcolumndlg, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (editcolumndlg, label37, "label37");
  GLADE_HOOKUP_OBJECT (editcolumndlg, id, "id");
  GLADE_HOOKUP_OBJECT (editcolumndlg, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (editcolumndlg, fmtlabel, "fmtlabel");
  GLADE_HOOKUP_OBJECT (editcolumndlg, format, "format");
  GLADE_HOOKUP_OBJECT (editcolumndlg, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (editcolumndlg, label38, "label38");
  GLADE_HOOKUP_OBJECT (editcolumndlg, align, "align");
  GLADE_HOOKUP_OBJECT (editcolumndlg, label25, "label25");
  GLADE_HOOKUP_OBJECT_NO_REF (editcolumndlg, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (editcolumndlg, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (editcolumndlg, okbutton1, "okbutton1");

  return editcolumndlg;
}

