#ifndef _AMIGAMSG_H_
#define _AMIGAMSG_H_

enum amigamsg {
  AMIGAMSG_SETSUBSONG = 1,
  AMIGAMSG_SONG_END,
  AMIGAMSG_PLAYERNAME,
  AMIGAMSG_MODULENAME,
  AMIGAMSG_SUBSINFO,
  AMIGAMSG_CHECKERROR,
  AMIGAMSG_SCORECRASH,
  AMIGAMSG_SCOREDEAD,
  AMIGAMSG_GENERALMSG,
  AMIGAMSG_NTSC,
  AMIGAMSG_FORMATNAME,
  AMIGAMSG_LOADFILE,
  AMIGAMSG_READ,
  AMIGAMSG_FILESIZE,
  AMIGAMSG_TIME_CRITICAL,
  AMIGAMSG_GET_INFO,
  AMIGAMSG_START_OUTPUT
};

#endif
