/* Generated by configure. Do not edit */
#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 20
#define PANGO_VERSION_MICRO 5

#define PANGO_VERSION_STRING "1.20.5"


#endif
