#!/bin/sh
rm /usr/local/lib/deadbeef/*.so
cp ./deadbeef /usr/local/bin/
cp ./plugins/nullout/.libs/nullout.so /usr/local/lib/deadbeef/
cp ./plugins/cdda/.libs/cdda.so /usr/local/lib/deadbeef/
cp ./plugins/flac/.libs/flac.so /usr/local/lib/deadbeef/
cp ./plugins/alsa/.libs/alsa.so /usr/local/lib/deadbeef/
cp ./plugins/mpgmad/.libs/mpgmad.so /usr/local/lib/deadbeef/
cp ./plugins/hotkeys/.libs/hotkeys.so /usr/local/lib/deadbeef/
cp ./plugins/vtx/.libs/vtx.so /usr/local/lib/deadbeef/
cp ./plugins/ffap/.libs/ffap.so /usr/local/lib/deadbeef/
cp ./plugins/wavpack/.libs/wavpack.so /usr/local/lib/deadbeef/
cp ./plugins/vorbis/.libs/vorbis.so /usr/local/lib/deadbeef/
cp ./plugins/oss/.libs/oss.so /usr/local/lib/deadbeef/
cp ./plugins/vfs_curl/.libs/vfs_curl.so /usr/local/lib/deadbeef/
cp ./plugins/ffmpeg/.libs/ffmpeg.so /usr/local/lib/deadbeef/
cp ./plugins/lastfm/.libs/lastfm.so /usr/local/lib/deadbeef/
cp ./plugins/sid/.libs/sid.so /usr/local/lib/deadbeef/
cp ./plugins/adplug/.libs/adplug.so /usr/local/lib/deadbeef/
cp ./plugins/gtkui/.libs/ddb_gui_GTK2.so /usr/local/lib/deadbeef/
cp ./plugins/sndfile/.libs/sndfile.so /usr/local/lib/deadbeef/
cp ./plugins/pulse/.libs/pulse.so /usr/local/lib/deadbeef/
cp ./plugins/artwork/.libs/artwork.so /usr/local/lib/deadbeef/
cp ./plugins/supereq/.libs/supereq.so /usr/local/lib/deadbeef/
cp ./plugins/gme/.libs/gme.so /usr/local/lib/deadbeef/
cp ./plugins/dumb/dumb.so /usr/local/lib/deadbeef/
cp ./plugins/notify/.libs/notify.so /usr/local/lib/deadbeef/
cp ./plugins/musepack/.libs/musepack.so /usr/local/lib/deadbeef/
cp ./plugins/wildmidi/.libs/wildmidi.so /usr/local/lib/deadbeef/
cp ./plugins/tta/.libs/tta.so /usr/local/lib/deadbeef/
cp ./plugins/dca/.libs/dca.so /usr/local/lib/deadbeef/
cp ./plugins/aac/.libs/aac.so /usr/local/lib/deadbeef/
cp ./plugins/mms/.libs/mms.so /usr/local/lib/deadbeef/
cp ./plugins/shn/shn.so /usr/local/lib/deadbeef/
cp ./plugins/ao/ao.so /usr/local/lib/deadbeef/
cp ./plugins/shellexec/.libs/shellexec.so /usr/local/lib/deadbeef/
cp ./plugins/dsp_libsrc/.libs/dsp_libsrc.so /usr/local/lib/deadbeef/
cp ./plugins/m3u/.libs/m3u.so /usr/local/lib/deadbeef/
cp ./plugins/ddb_input_uade2/ddb_input_uade2.so /usr/local/lib/deadbeef/
cp ./plugins/converter/.libs/converter.so /usr/local/lib/deadbeef/
cp ./plugins/converter/.libs/converter_gtkui.so /usr/local/lib/deadbeef/
cp ./plugins/soundtouch/ddb_soundtouch.so /usr/local/lib/deadbeef/
cp ./plugins/vfs_zip/.libs/vfs_zip.so /usr/local/lib/deadbeef/
cp ./plugins/mono2stereo/mono2stereo.so /usr/local/lib/deadbeef/
