/* WARNING: autogenerated file */
#include "duktape.h"
#include "../../deadbeef.h"

#include "bindings.h"

extern DB_functions_t *deadbeef;

void bind_int_constants (duk_context *ctx) {
    duk_push_global_object(ctx);
    duk_push_int(ctx, DDB_TAG_VORBISCOMMENTS);
    duk_put_prop_string(ctx, -2, "TAG_VORBISCOMMENTS");
    duk_push_int(ctx, DDB_TAG_ID3V1);
    duk_put_prop_string(ctx, -2, "TAG_ID3V1");
    duk_push_int(ctx, DB_API_VERSION_MAJOR);
    duk_put_prop_string(ctx, -2, "API_VERSION_MAJOR");
    duk_push_int(ctx, DDB_TAG_ITUNES);
    duk_put_prop_string(ctx, -2, "TAG_ITUNES");
    duk_push_int(ctx, PL_SEARCH);
    duk_put_prop_string(ctx, -2, "PL_SEARCH");
    duk_push_int(ctx, PL_MAIN);
    duk_put_prop_string(ctx, -2, "PL_MAIN");
    duk_push_int(ctx, DDB_TAG_ID3V23);
    duk_put_prop_string(ctx, -2, "TAG_ID3V23");
    duk_push_int(ctx, DDB_TAG_ID3V22);
    duk_put_prop_string(ctx, -2, "TAG_ID3V22");
    duk_push_int(ctx, DDB_IS_SUBTRACK);
    duk_put_prop_string(ctx, -2, "IS_SUBTRACK");
    duk_push_int(ctx, DB_API_VERSION_MINOR);
    duk_put_prop_string(ctx, -2, "API_VERSION_MINOR");
    duk_push_int(ctx, DDB_TAG_ICY);
    duk_put_prop_string(ctx, -2, "TAG_ICY");
    duk_push_int(ctx, DDB_TAG_MASK);
    duk_put_prop_string(ctx, -2, "TAG_MASK");
    duk_push_int(ctx, DDB_IS_READONLY);
    duk_put_prop_string(ctx, -2, "IS_READONLY");
    duk_push_int(ctx, DDB_API_LEVEL);
    duk_put_prop_string(ctx, -2, "API_LEVEL");
    duk_push_int(ctx, DDB_HAS_EMBEDDED_CUESHEET);
    duk_put_prop_string(ctx, -2, "HAS_EMBEDDED_CUESHEET");
    duk_push_int(ctx, DDB_TAG_ID3V24);
    duk_put_prop_string(ctx, -2, "TAG_ID3V24");
    duk_push_int(ctx, DDB_TAG_APEV2);
    duk_put_prop_string(ctx, -2, "TAG_APEV2");
    duk_push_int(ctx, DDB_TAG_CUESHEET);
    duk_put_prop_string(ctx, -2, "TAG_CUESHEET");
    duk_pop(ctx);
}

int
js_impl_plt_get_count (duk_context *ctx) {
    int ret = deadbeef->plt_get_count ();
    js_return_int_value (ctx, ret);
    return 1;
}

int
js_impl_playback_set_pos (duk_context *ctx) {
    float arg0 = js_init_float_argument (ctx, 0);
    deadbeef->playback_set_pos (arg0);
    return 0;
}

int
js_impl_streamer_get_apx_bitrate (duk_context *ctx) {
    int ret = deadbeef->streamer_get_apx_bitrate ();
    js_return_int_value (ctx, ret);
    return 1;
}

int
js_impl_streamer_set_bitrate (duk_context *ctx) {
    int arg0 = js_init_int_argument (ctx, 0);
    deadbeef->streamer_set_bitrate (arg0);
    return 0;
}

int
js_impl_streamer_get_playpos (duk_context *ctx) {
    float ret = deadbeef->streamer_get_playpos ();
    js_return_float_value (ctx, ret);
    return 1;
}

int
js_impl_streamer_reset (duk_context *ctx) {
    int arg0 = js_init_int_argument (ctx, 0);
    deadbeef->streamer_reset (arg0);
    return 0;
}

int
js_impl_streamer_ok_to_read (duk_context *ctx) {
    int arg0 = js_init_int_argument (ctx, 0);
    int ret = deadbeef->streamer_ok_to_read (arg0);
    js_return_int_value (ctx, ret);
    return 1;
}

int
js_impl_streamer_read (duk_context *ctx) {
    jscharbuffer arg0 = js_init_jscharbuffer_argument (ctx, 0);
    int arg1 = js_init_int_argument (ctx, 1);
    int ret = deadbeef->streamer_read (arg0, arg1);
    js_return_int_value (ctx, ret);
    return 1;
}

int
js_impl_playback_get_pos (duk_context *ctx) {
    float ret = deadbeef->playback_get_pos ();
    js_return_float_value (ctx, ret);
    return 1;
}

int
js_impl_streamer_get_streaming_track (duk_context *ctx) {
    DB_playItem_t* ret = deadbeef->streamer_get_playing_track ();
    js_return_DB_playItem_t_ptr_value (ctx, ret);
    return 1;
}

int
js_impl_get_output (duk_context *ctx) {
    DB_output_t* ret = deadbeef->get_output ();
    js_return_DB_output_t_ptr_value (ctx, ret);
    return 1;
}

void bind_functions (duk_context *ctx) {
    duk_push_global_object(ctx);
    duk_push_c_function(ctx, js_impl_plt_get_count, 0);
    duk_put_prop_string(ctx, -2, "plt_get_count");
    duk_push_c_function(ctx, js_impl_playback_set_pos, 0);
    duk_put_prop_string(ctx, -2, "playback_set_pos");
    duk_push_c_function(ctx, js_impl_streamer_get_apx_bitrate, 0);
    duk_put_prop_string(ctx, -2, "streamer_get_apx_bitrate");
    duk_push_c_function(ctx, js_impl_streamer_set_bitrate, 0);
    duk_put_prop_string(ctx, -2, "streamer_set_bitrate");
    duk_push_c_function(ctx, js_impl_streamer_get_playpos, 0);
    duk_put_prop_string(ctx, -2, "streamer_get_playpos");
    duk_push_c_function(ctx, js_impl_streamer_reset, 0);
    duk_put_prop_string(ctx, -2, "streamer_reset");
    duk_push_c_function(ctx, js_impl_streamer_ok_to_read, 0);
    duk_put_prop_string(ctx, -2, "streamer_ok_to_read");
    duk_push_c_function(ctx, js_impl_streamer_read, 0);
    duk_put_prop_string(ctx, -2, "streamer_read");
    duk_push_c_function(ctx, js_impl_playback_get_pos, 0);
    duk_put_prop_string(ctx, -2, "playback_get_pos");
    duk_push_c_function(ctx, js_impl_streamer_get_streaming_track, 0);
    duk_put_prop_string(ctx, -2, "streamer_get_streaming_track");
    duk_push_c_function(ctx, js_impl_get_output, 0);
    duk_put_prop_string(ctx, -2, "get_output");
    duk_pop(ctx);
}

void duktape_bind_all (duk_context *ctx) {
    bind_int_constants(ctx);
    bind_functions(ctx);
}

