FROM deadbeef-builder-player-clang-14.04-distro

WORKDIR /usr/src/deadbeef
COPY . /usr/src/deadbeef

RUN rm -rf m4
RUN rm ltmain.sh
RUN ./autogen.sh
RUN CC=clang ./configure
RUN CC=clang make distcheck

