FROM deadbeef-builder-player-clang-14.04-distro

RUN apt-get -qq update
RUN apt-get install -y -qq libgtk-3-dev

WORKDIR /usr/src/deadbeef
COPY . /usr/src/deadbeef

RUN rm -rf m4
RUN rm ltmain.sh
RUN ./autogen.sh
RUN CC=clang ./configure
RUN CC=clang make distcheck

