void line700(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((0&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line701(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((1&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line702(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((2&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line703(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((3&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line704(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((4&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line705(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((5&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line706(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((6&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line707(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((7&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line708(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((8&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line709(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((9&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line70A(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((10&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line70B(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((11&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line70C(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((12&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line70D(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((13&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line70E(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((14&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line70F(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((15&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line710(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((16&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line711(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((17&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line712(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((18&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line713(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((19&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line714(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((20&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line715(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((21&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line716(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((22&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line717(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((23&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line718(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((24&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line719(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((25&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line71A(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((26&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line71B(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((27&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line71C(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((28&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line71D(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((29&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line71E(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((30&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line71F(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((31&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line720(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((32&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line721(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((33&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line722(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((34&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line723(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((35&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line724(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((36&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line725(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((37&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line726(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((38&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line727(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((39&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line728(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((40&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line729(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((41&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line72A(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((42&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line72B(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((43&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line72C(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((44&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line72D(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((45&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line72E(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((46&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line72F(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((47&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line730(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((48&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line731(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((49&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line732(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((50&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line733(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((51&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line734(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((52&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line735(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((53&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line736(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((54&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line737(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((55&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line738(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((56&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line739(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((57&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line73A(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((58&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line73B(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((59&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line73C(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((60&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line73D(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((61&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line73E(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((62&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

void line73F(u32 reg9, u32 reg0)
{
  /* MOVEQ #xx,Dn */
  s32 a=(s32)(s8) (reg0+((63&31)<<3));
  reg68.d[reg9] = a;
  MOVE(a)
}

